version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./public:/public
      - ./composer/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./public:/public